version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achatdb
    ports:
      - 8082:8082
    volumes:
      - db:/var/lib/mysql

  app:
    depends_on:
      - mysqldb
    image: emnarah/achat:1.0.0
    restart: on-failure
    ports:
      - 3306:3306
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url": "jdbc:mysql://localhost:3306/achatdb?createDatabaseIfNotExist=true",
          "spring.datasource.username": "root",
          "spring.datasource.password": "",
          "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
          "spring.jpa.hibernate.ddl-auto": "update"
        }'
    stdin_open: true
    tty: true

volumes:
  db:
networks:
  custom_network:
    driver: bridge